<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{

    public function run(): void
    {
        $products = [
            ['name' => 'Keyboard Medis Silikon', 'description' => 'Keyboard Medis Silikon Nirkabel dengan Bantalan Belakang Sesuai dengan Ergonomi', 'price' => 100.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00HdbioPTChpqr/Wireless-Silicone-Medical-Keyboard-with-Back-Pad-According-with-Ergonomics.webp'],
            ['name' => 'Keyboard Metalik Tanpa Suara', 'description' => 'Tombol Keyboard Kunci Persegi, Tekstur Metalik, 2.4G Nirkabel, Bertenaga Baterai, Tanpa Suara untuk Kantor Publik', 'price' => 7.25, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00GmDCMKlPEIoL/Square-Keycap-Scissor-Keyboard-Metallic-Texture-2-4G-Wireless-Battery-Powered-Noiseless-for-Public-Office.webp'],
            ['name' => 'Keyboard Mekanik Gasket Mount', 'description' => 'Keyboard Mekanik Nirkabel USB 3.0 Dapat Dipindah Gasket Mount Tata Letak Khusus Gaming Penggunaan Per Kunci Kombinasi Esports', 'price' => 38.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00QAPkSnbGhzpr/New-Wireless-Mechanical-Keyboard-USB-3-0-Hot-Swappable-Gasket-Mount-Layout-Gaming-Specific-Use-Per-Key-Esports-Combo.webp'],
            ['name' => 'Kombinasi Keyboard & Mouse Ergonomis', 'description' => 'Kombinasi Keyboard Mekanik Nirkabel dan Mouse Ukuran Penuh Desain Ergonomis untuk Penggunaan Tablet Laptop Permainan Kantor Penggunaan Permainan', 'price' => 10.31, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00HwpoBAbhADuU/Wireless-Mechanical-Keyboard-Mouse-Combo-Full-Size-Ergonomic-Design-Tablet-Laptop-Use-Gaming-Office-Gaming-Usage.webp'],
            ['name' => 'Keyboard Ultra Tipis Tri-Mode', 'description' => 'Keyboard Ultra Tipis Tri Mode Scissor Witch Baru Ukuran Penuh Metal untuk Penggunaan Desktop Mac Nirkabel dan Berkabel Umum Gaming Kantor', 'price' => 30.94, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00BdokNfWgrRzw/Scissor-Witch-Tri-Mode-Ultra-Thin-Keyboard-New-Full-Size-Metal-for-Mac-Wired-Wireless-Desktop-Use-General-Gaming-Office.webp'],
            ['name' => 'Keyboard RGB 4 Saluran', 'description' => 'Meja Geser Baru 4 Saluran Keyboard Nirkabel RGB Backlit USB Kombinasi Desktop Tablet Laptop Ponsel Nilai Tinggi Penggunaan Kantor', 'price' => 6.79, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TfDVMZKgHkqR/New-Sliding-Desk-4-Channel-Wireless-Keyboard-RGB-Backlit-USB-Combo-Desktop-Tablet-Laptop-Phone-High-Value-Office-Use.webp'],
            ['name' => 'Set Keyboard & Mouse Bisnis', 'description' => '2.4G Set Keyboard dan Mouse Sentuh Mekanik Ukuran Penuh USB Nirkabel Baru untuk Penggunaan Bisnis Kantor Baru dengan Penyangga Pergelangan Tangan', 'price' => 7.45, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00sOfitLclqHbz/2-4G-Wireless-USB-New-Full-Size-Mechanical-Feel-Keyboard-and-Mouse-Set-for-New-Office-Business-Use-with-Wrist-Rest.webp'],
            ['name' => 'Keyboard Mekanik Mode Ganda', 'description' => 'Keyboard Mekanik Nirkabel 2.4G Mode Ganda Daya Tahan Lama Kunci Senyap', 'price' => 18.43, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00VjhkStPzEobL/2-4G-Wireless-Mechanical-Keyboard-Dual-Mode-Long-Endurance-Silent-Key.webp'],
            ['name' => 'Keyboard Bluetooth Lipat Portabel', 'description' => 'Kunci Sudut Bulat Dua Hadiah Lipat Penyambungan Tanpa Seam Keyboard Bluetooth Nirkabel Portabel', 'price' => 15.85, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00lGakfAtCHpqz/Round-Corner-Key-Two-Folding-Gifts-Seamless-Splicing-Portable-Wireless-Bluetooth-Keyboard.webp'],
            ['name' => 'Transmitter Panggilan K-999', 'description' => 'Transmitter Panggilan Nirkabel Multifungsi Keypad Keyboard K-999', 'price' => 45.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TbfCMZpLAbke/Multifunctional-Wireless-Calling-Transmitter-Keypad-Keyboard-K-999.webp'],
            ['name' => 'Keyboard Lipat Mini (Touchpad)', 'description' => 'Harga Pabrik Keyboard Lipat Nirkabel Slim Mini Portabel dengan Touchpad dan Kustomisasi OEM ODM', 'price' => 24.5, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00SjVkSAbPHDoz/Factory-Price-Portable-Mini-Slim-Wireless-Folding-Keyboard-with-Touchpad-and-OEM-ODM-Customization.webp'],
            ['name' => 'Keyboard Mini Nirkabel H9', 'description' => 'H9 Keyboard Mini Nirkabel Berlampu Warna dengan Touch', 'price' => 5.8, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00BfDCMZKAHDoz/H9-Color-Backlit-Wireless-Mini-Keyboard-with-Touch.webp'],
            ['name' => 'Keyboard Kulit iPad Pro', 'description' => 'Keyboard Nirkabel Kulit Sentuh Tablet PC Ajaib untuk iPad PRO 11/10.9', 'price' => 30.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00IbfVAbvEHpoz/Magic-Touch-Leather-Wireless-Keyboard-Tablet-PC-for-iPad-PRO-11-10-9.webp'],
            ['name' => 'Keyboard Bluetooth Warna-warni', 'description' => 'Grosir Murah Pink Hitam 7 8 9 10inch Keyboard Nirkabel Portable Keyboard Koneksi Bluetooth', 'price' => 1.85, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00HdboNclEHDoz/Wholesale-Cheap-Pink-Black-7-8-9-10inch-Wireless-Keyboard-Portable-Keyboard-Bluetooth-Connection.webp'],
            ['name' => 'Keyboard Ajaib (Touch ID)', 'description' => 'Keyboard Ajaib dengan Touch ID dan Numpad Nirkabel untuk Komputer Mac', 'price' => 200.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00LInGvclEhAbq/Magic-Keyboard-with-Touch-ID-and-Numeric-Keypad-Wireless-for-Mac-Computer.webp'],
            ['name' => 'Keyboard Mini RGB Rechargeable', 'description' => 'Keyboard Nirkabel Bluetooth Mini Portabel dengan Lampu Latar RGB yang Dapat Diisi Ulang untuk iPad Notebook Laptop', 'price' => 3.7, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TbfVnclEHDoz/Mini-Portable-Wireless-Bluetooth-Keyboard-with-Rechargeable-RGB-Backlight-for-iPad-Notebook-Laptop.webp'],
            ['name' => 'Keyboard Slim Tombol Bulat', 'description' => 'Keyboard Nirkabel Bluetooth Terlaris untuk Penggunaan Kantor dan Rumah dengan Desain Slim dan Tombol Bulat Datar', 'price' => 8.9, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TfDiAfKPHDoz/Best-Selling-Bluetooth-Wireless-Keyboard-for-Office-and-Home-Use-with-Slim-Design-and-Flat-Round-Buttons.webp'],
            ['name' => 'Keyboard Trackpad iPad 12.9', 'description' => 'Trackpad Keyboard Bluetooth Nirkabel untuk iPad 12.9 2020/2021', 'price' => 45.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00IbfVMZpLHDoz/Wireless-Bluetooth-Keyboard-Trackpad-for-iPad-12-9-2020-2021.webp'],
            ['name' => 'Keyboard Mini Portabel ABS', 'description' => 'Keyboard Nirkabel Mini Slim Portabel Terlaris ABS untuk Mac PC iPhone iPad Ios Android Windows untuk Gaming Keyboard Mouse Bluetooth', 'price' => 1.95, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00VfhkSAbLHDoz/Best-Selling-Portable-Mini-Slim-Wireless-Keyboard-ABS-for-Mac-PC-iPhone-iPad-Ios-Android-Windows-for-Gaming-Keyboard-Mouse-Bluetooth.webp'],
            ['name' => 'Keyboard Lipat B055', 'description' => 'B055 Keyboard Nirkabel Bluetooth Tipis Ultra Lipat untuk Tablet PC dengan Touchpad, Keyboard Lipat Mini Portabel', 'price' => 34.7, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00HfDaAclEHDoz/B055-Ultra-Foldable-Slim-Bluetooth-Wireless-Keyboard-for-Tablet-PC-with-Touchpad-Portable-Mini-Folding-Keyboard.webp'],
            ['name' => 'Keyboard Lipat 64 Tombol', 'description' => 'Bagian Komputer Mini Portabel Lipat Dapat Diisi Ulang 64 Kunci Keyboard Nirkabel Bluetooth dengan Touchpad untuk Windows Android Ios Telepon', 'price' => 23.6, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00IdfVMAbEHDoz/Rechargeable-Foldable-Portable-Mini-Computer-Parts-64-Keys-Wireless-Bluetooth-Keyboard-with-Touchpad-for-Windows-Android-Ios-Phone.webp'],
            ['name' => 'Keyboard Magnetik iPad Air 2024', 'description' => 'Keyboard Nirkabel Magnetik Multi Sentuh dengan Penutup Pelindung Kulit Premium untuk iPad Air 13 2024/PRO 12.9 2020', 'price' => 42.6, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TbfCMAbLHDoz/Multi-Touch-Magnetic-Wireless-Keyboard-with-Premium-Leather-Protective-Cover-for-iPad-Air-13-2024-PRO-12-9-2020.webp'],
            ['name' => 'Kit Keyboard & Mouse Fashion', 'description' => 'Promosi Kit Papan Ketik dan Alas Mouse Bluetooth Nirkabel Fashion Murah Grosir', 'price' => 3.7, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00fDfCMZpLHDoz/Promotion-Wholesale-Cheap-Fashion-Wireless-Bluetooth-Keyboard-and-Mousepad-Kit.webp'],
            ['name' => 'Keyboard Mini i8 Touchpad', 'description' => '7 Warna Terang 2.4G Keyboard Mini Nirkabel Bluetooth I8 Touchpad Mouse Udara untuk Kotak TV Android', 'price' => 3.3, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00HdfViAflHkoz/7-Color-Light-2-4G-Wireless-Mini-Keyboard-Bluetooth-I8-Touchpad-Air-Mouse-for-Android-TV-Box.webp'],
            ['name' => 'Keyboard Tipis Kunci Cokelat', 'description' => 'Keyboard Nirkabel Ultra Tipis Nyaman Penuh Ukuran Tipis Kunci Cokelat 2.4GHz Keyboard', 'price' => 5.9, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00oBhkVfbqALkz/Comfortable-Ultra-Thin-Wireless-Keyboard-Full-Size-Slim-Chocolate-Key-2-4GHz-Keyboard.webp'],
            ['name' => 'Keyboard Bluetooth iPad Slim', 'description' => 'Desain Ultra Tipis Terbaru Keyboard Nirkabel Bluetooth untuk iPad Kantor dan Rumah Laptop', 'price' => 13.6, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TfhkSfKEHDoz/Latest-Ultra-Slim-Design-Wireless-Bluetooth-Keyboard-for-iPad-Office-and-Home-Laptop.webp'],
            ['name' => 'Keyboard Medis Anti Virus', 'description' => 'Keyboard Medis Anti Virus Tahan Air Bluetooth Nirkabel', 'price' => 55.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00IdfCMZKEHkoz/Wireless-Bluetooth-Waterproof-Anti-Virus-Medical-Keyboard.webp'],
            ['name' => 'Keyboard Desktop Tidur Otomatis', 'description' => 'Keyboard Desktop Bluetooth Nirkabel Tidur Otomatis Efisien dengan 2h Pengisian Cepat', 'price' => 21.43, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00TfDiSclEHDoz/Efficient-Auto-Sleep-Wireless-Bluetooth-Desktop-Keyboard-with-2h-Fast-Charging.webp'],
            ['name' => 'Keyboard Kantor Bluetooth (Touchpad)', 'description' => 'Keyboard Kantor Nirkabel Bluetooth dengan Touchpad untuk Telepon dan Tablet', 'price' => 19.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00BbfVnMplHDoz/Bluetooth-Wireless-Office-Keyboard-with-Touchpad-for-Phone-and-Tablet.webp'],
            ['name' => 'Keyboard & Mouse Kantor Ekonomis', 'description' => 'Pabrik Keyboard & Mouse Termurah untuk Kantor Rumah Desktop Laptop Alas Mouse 2.4G Keyboard Mouse Nirkabel USB', 'price' => 5.1, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00RbfitclEHkoz/Cheapest-Keyboard-Mouse-Factory-for-Office-Home-Desktop-Laptop-Mouse-Pad-2-4G-USB-Wireless-Keyboard-Mouse.webp'],
            ['name' => 'Case Keyboard Kulit PU iPad', 'description' => 'Kasing Kulit PU Keyboard Nirkabel Bluetooth untuk iPad Air 4 PRO 11 10 Gen', 'price' => 8.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00IbfViMZLAboz/PU-Leather-Case-Wireless-Bluetooth-Keyboard-for-iPad-Air-4-PRO-11-10-Gen.webp'],
            ['name' => 'Keyboard Bluetooth Premium', 'description' => 'Keyboard Nirkabel Bluetooth Berkualitas Tinggi dengan Touchpad untuk Telepon dan Tablet', 'price' => 19.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00BbfVnMplHDoz/High-Quality-Wireless-Bluetooth-Keyboard-with-Touchpad-for-Phone-and-Tablet.webp'],
            ['name' => 'Keyboard USB Multi-Bahasa', 'description' => 'Desain Mode Papan Ketik Prancis Spanyol Jerman Keypad Komputer 2.4G Keyboard Nirkabel USB Mouse', 'price' => 5.1, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00RbfitclEHkoz/Fashion-Design-French-Spanish-German-Keyboard-Computer-Keypad-2-4G-Wireless-USB-Keyboard-Mouse.webp'],
            ['name' => 'Keyboard Desktop Mode Ganda', 'description' => 'Keyboard Kantor Desktop Nirkabel Bluetooth Mode Ganda Plug-and-Play, Tanpa Diperlukan Driver', 'price' => 20.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00BbgCKEGJZpkh/Plug-and-Play-Wireless-Bluetooth-Dual-Mode-Desktop-Office-Keyboard-No-Driver-Needed.webp'],
            ['name' => 'Keyboard Mini Full Size', 'description' => 'Keyboard Bluetooth Nirkabel Mini Ukuran Penuh Berkualitas Tinggi untuk Telepon dan Tablet', 'price' => 7.0, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00NnsktboWrcuI/High-Quality-Full-Size-Mini-Bluetooth-Wireless-Keyboard-for-Phone-and-Tablet.webp'],
            ['name' => 'Kombinasi Keyboard & Mouse 2.4G', 'description' => '2.4G Kombinasi Keyboard dan Mouse Nirkabel untuk Sistem Mac/Windows', 'price' => 5.9, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00RqMiAzFEbyfG/2-4G-Wireless-Keyboard-and-Mouse-Combo-for-Mac-Windows-System.webp'],
            ['name' => 'Keyboard Ultra Tipis Rechargeable', 'description' => 'Keyboard Nirkabel Bluetooth Ultra Tipis yang Dapat Diisi Ulang untuk iPad, Tablet Android, Telepon Seluler, dan MacBook', 'price' => 5.99, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00oBchMTOsAEkI/Ultra-Slim-Rechargeable-Wireless-Bluetooth-Keyboard-for-iPad-Android-Tablet-Mobile-Phone-for-MacBook.webp'],
            ['name' => 'Keyboard Gaming RGB 63 Tombol', 'description' => 'Desain Keyboard Gaming Mekanik Nirkabel RGB yang Elegan 63-Key', 'price' => 22.47, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00RqhiAbGqADoz/Elegant-Design-Wireless-RGB-Mechanical-Gaming-Keyboard-63-Key.webp'],
            ['name' => 'Keyboard Mini Tri-Fold', 'description' => 'Keyboard Mini Nirkabel Lipat Tri-Fold dengan Touchpad untuk Telepon Seluler Apple', 'price' => 17.99, 'stock' => 100, 'image' => 'https://image.made-in-china.com/201f0j00SjhVAbvEHpoz/Tri-Fold-Folding-Wireless-Mini-Keyboard-with-Touchpad-for-Apple-Mobile-Phone.webp'],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}